# Generated by Django 5.1.3 on 2024-11-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField()),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=25)),
                ('cuisine', models.CharField(max_length=25)),
            ],
        ),
    ]
