# Generated by Django 5.1.3 on 2024-11-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='type',
            new_name='gender',
        ),
    ]
