# Generated by Django 5.1.3 on 2024-11-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_rename_type_meals_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='price',
            field=models.TextField(),
        ),
    ]
